#server:
#  port: 8080
#spring:
#  jpa:
#    properties:
#      hibernate:
#        default_schema: flutter
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#  datasource:
#    url: ${url}
#    driver-class-name: org.postgresql.Driver
#    username: ${username}
#    password: ${password}
#  h2:
#    console.enabled: true

server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: ${url}
    driver-class-name: org.postgresql.Driver
    username: ${username}
    password: ${password}
  h2:
    console.enabled: true